apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: smq8drq0d-python
  janus-idp.io/tekton: smq8drq0d-python
  backstage.io/kubernetes-id: smq8drq0d-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: smq8drq0d-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
